"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { CopyIcon, CheckIcon } from "lucide-react";
import type { PRSummary } from "@/services/api";

interface CopySummaryButtonProps {
  summary: PRSummary;
  prTitle: string;
  prNumber: number;
  repoOwner: string;
  repoName: string;
  author: string;
}

export function CopySummaryButton({
  summary,
  prTitle,
  prNumber,
  repoOwner,
  repoName,
  author,
}: CopySummaryButtonProps) {
  const [copied, setCopied] = useState(false);

  const formatSummaryAsMarkdown = () => {
    const lines = [
      `# PR #${prNumber}: ${prTitle}`,
      "",
      `**Repository:** ${repoOwner}/${repoName}`,
      `**Author:** @${author}`,
      `**Risk Level:** ${summary.riskLevel.toUpperCase()}`,
      summary.breakingChanges ? "**⚠️ Contains Breaking Changes**" : "",
      "",
      "## Summary",
      "",
      summary.summary,
      "",
    ];

    if (summary.keyChanges && summary.keyChanges.length > 0) {
      lines.push("## Key Changes", "");
      summary.keyChanges.forEach((change) => {
        lines.push(`- ${change}`);
      });
      lines.push("");
    }

    if (summary.filesChanged && summary.filesChanged.length > 0) {
      lines.push("## Files Changed", "");
      summary.filesChanged.forEach((file) => {
        const icon =
          file.changeType === "added"
            ? "+"
            : file.changeType === "deleted"
            ? "-"
            : "~";
        lines.push(`- \`${file.name}\` (${icon} ${file.changeType})`);
      });
      lines.push("");
    }

    lines.push(
      "---",
      `*Generated by SnapDocs on ${new Date(summary.generatedAt).toLocaleDateString()}*`
    );

    return lines.filter(Boolean).join("\n");
  };

  const handleCopy = async () => {
    try {
      const markdown = formatSummaryAsMarkdown();
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error("Failed to copy:", error);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleCopy}
      className="w-full"
    >
      {copied ? (
        <>
          <CheckIcon className="h-4 w-4 mr-2 text-green-500" />
          Copied!
        </>
      ) : (
        <>
          <CopyIcon className="h-4 w-4 mr-2" />
          Copy Summary
        </>
      )}
    </Button>
  );
}
